name: Cross-build loongarch64 kernel
on: [pull_request, create]

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Cross-build loongarch64 kernel
    runs-on: ubuntu-24.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc bc bison flex elfutils python3-pyelftools curl patch libelf-dev

      - name: Install loongarch64 cross-compilation toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc-13-loongarch64-linux-gnu -y
          sudo update-alternatives \
            --install /usr/bin/loongarch64-linux-gnu-gcc loongarch64-linux-gnu-gcc /usr/bin/loongarch64-linux-gnu-gcc-13 100 \
            --slave /usr/bin/loongarch64-linux-gnu-gcc-ar loongarch64-linux-gnu-gcc-ar /usr/bin/loongarch64-linux-gnu-gcc-ar-13 \
            --slave /usr/bin/loongarch64-linux-gnu-gcc-nm loongarch64-linux-gnu-gcc-nm /usr/bin/loongarch64-linux-gnu-gcc-nm-13 \
            --slave /usr/bin/loongarch64-linux-gnu-gcc-ranlib loongarch64-linux-gnu-gcc-ranlib /usr/bin/loongarch64-linux-gnu-gcc-ranlib-13 \
            --slave /usr/bin/loongarch64-linux-gnu-gcov loongarch64-linux-gnu-gcov /usr/bin/loongarch64-linux-gnu-gcov-13
          sudo update-alternatives \
            --install /usr/bin/loongarch64-linux-gnu-cpp loongarch64-linux-gnu-cpp /usr/bin/loongarch64-linux-gnu-cpp-13 100

      - name: Build loongarch64 kernel
        run: make ARCH=loongarch CROSS_COMPILE=loongarch64-linux-gnu-
